export const TAGS = {
  USERS: 'USERS',
  GET_ME: 'GET_ME',
  CREATE_ME: 'CREATE_ME',
  LOG_IN: 'LOG_IN',
  SCHEDULES: 'SCHEDULES',
  COURTS: 'COURTS',
  COURT: 'COURT',
  JOBS: 'JOBS',
  PAYMENT_METHOD: 'PAYMENT_METHOD',
  VISITORS: 'VISITORS',
};
